apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xcvx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0028-tenant/tkrw-pr712-0075-0028-app/devfile-sample-xcvx@sha256:8deccd48b025a252404563f351975a18c6d059a6d7691583e7254dbea46dcc2a
        name: my-nodejs
        resources: {}
status: {}
